# Generated by Django 5.0 on 2024-01-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
